[project]
name = "monitor-automatico"
version = "0.1.0"
description = "Monitora processos python ativos e avisa, por email, quando termina."
authors = [
    {name = "rafael.rafarod@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil (>=7.2.2,<8.0.0)",
    "keyring (>=25.7.0,<26.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
